language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: iRltDxM6mMgS9GFuX9Q6JpILwfshM/nqO+sjCdfnyomqmtPdM0krLpj8yb7FkeaNgcpBcbIbpemtb5d7vVkj3NNdQzvy0oEFJ3WpOgzvE0VjU8xi5Pw6pPLaCKJjX9NBLz8cXzb6Pj3C90Jv/slqW5Dr2TEDToTqZaQudD/SdEDYVv8VYhyQTTClFmt1EmBuYcoqo5aPeiKeIrhOGn04izXc3VxCiGhKWt/2dqihRG9Mg+kr19BMFM2EfAKTKxkunDQf/p8DjOwRfvQIUM43NnCUPquTUMGIDqr5iSb3NZYTXdC9fx6dr3eUWqPHyXTEcVucU4VhLtF/19n4JiVOWwJJ5IYJbY4QQHKYJ5AGkM22k4e6Go6p4tYqhwx1iHG87ui5vNXjPsgdYfN09fX5aQ3Kcr9HaJjSIGqtNEk7LV8kxxPsg03mnR920gDBfUEzjjwQkYDMJ1e1FOrUXU5IgREHsnRo5KV/xUtYTckWkZzfn/x/6mDWJ7eYDXcNdieks0tDfXLxKTklqnf0aVjM8hq4yI+EH0tsl4J/yzxR5hni5R6ykkzcF8cuQeRqJX1GdFpcdCv3z4ITZf5J2a+PNb/UT7gLldJRUjjfc4h6R7mSwmPvpR+QzAAqLXKqD8seYGh/SgqKQkePT8hfKs/xWVLJ0Te27k/MjJ2bX22T6QE=
  app: shrouded-shelf-93621
  on:
    repo: msolorio/blogPostApi
